#!/usr/bin/env python3
"""Build the English Snatcher image: code patch + names + every scene + (optionally) the English voices.

  build_all.py              -> build-en/   (multi-bin, for the emulator), English voices included
  VOICE=0 build_all.py      -> text only, much faster, for checking a text change

The voices are on by default because a build without them is not a thing anyone wants to play: it looks
translated and every spoken line is Japanese, which is exactly how it was shipped to the card once
(21 Sep) after a bare `build_all.py`. The same run also relinks tracks 03-20 to the Japanese originals,
so `intro_audio.py` and `cutscene_dub.py` have to run again after this -- it says so when it finishes.

Per scene: the menu words are rewritten in place where the English fits (else they move into the slack),
then the whole text area is re-encoded message by message (tools/snhuff.py) and every say command
`12 <speaker> 00 <lo> <hi>` re-pointed. Scene data comes from work/scenes/<lba>.json (the game's own scene
table), English from translations/scenes/<lba>.tsv. Scenes with identical Japanese share one translation.
"""
import glob
import json
import os
import shutil
import sys

sys.path.insert(0, __file__.rsplit("/", 1)[0])
import cdsector as C  # noqa: E402
import sncells  # noqa: E402
import keyboard  # noqa: E402
import namesearch  # noqa: E402
import answers  # noqa: E402
import scene_copies  # noqa: E402
import title_patch  # noqa: E402
import snhack  # noqa: E402
import snhuff  # noqa: E402
import snnames  # noqa: E402

N = "Snatcher CD-ROMantic (Japan)"


def load_tsv(path):
    words, msgs = {}, {}
    for line in open(path):
        line = line.rstrip("\n")
        if not line.strip() or line.startswith("#"):
            continue
        kind, key, *rest = line.split("\t")
        text = rest[-1] if rest else ""
        (words if kind == "W" else msgs)[int(key, 16)] = text
    return words, msgs


# Where the English comes from. work/scenes_resolved is generated by tools/resolve_refs.py out of
# translations/scenes_ref + the user's own Sega CD disc, and it WINS over translations/scenes when it
# exists -- which silently swallowed a hand retranslation of the Gibson records once. The build says
# which directory it used, and warns when the hand-edited files are newer than the generated ones.
SCENES_DIR = os.environ.get("SCENES", "work/scenes_resolved" if os.path.isdir("work/scenes_resolved")
                            else "translations/scenes")


def text_source():
    """Which directory the English came from, and whether a hand edit is being ignored.

    Compared by content, not by date: a file that merely looks older is fine, a line that says something
    different is not -- that is how a retranslation of the Gibson records sat unbuilt for a day.
    """
    note = f"text from {SCENES_DIR}"
    if SCENES_DIR == "translations/scenes" or not os.path.isdir("translations/scenes"):
        return note
    differ = []
    for hand in sorted(glob.glob("translations/scenes/*.tsv")):
        gen = f"{SCENES_DIR}/{os.path.basename(hand)}"
        if not os.path.exists(gen):
            continue
        a, b = load_tsv(hand), load_tsv(gen)
        if a[0] != b[0] or a[1] != b[1]:
            differ.append(os.path.basename(hand))
    if differ:
        note += (f"  -- WARNING: {len(differ)} file(s) in translations/scenes say something different "
                 f"and are being ignored ({', '.join(differ[:4])})")
    return note


def translation_for(lba, scenes):
    """The scene's own file, or that of the scene with identical Japanese text."""
    p = f"{SCENES_DIR}/{lba:03x}.tsv"
    if os.path.exists(p):
        return load_tsv(p)
    key = "".join(m["jp"] for m in scenes[lba]["messages"])
    for other, sc in scenes.items():
        if other != lba and "".join(m["jp"] for m in sc["messages"]) == key:
            q = f"{SCENES_DIR}/{other:03x}.tsv"
            if os.path.exists(q):
                w, m = load_tsv(q)
                # same text, possibly different offsets: map by position
                wmap = {a["off"]: b for a, b in zip(scenes[lba]["words"], w.values())}
                mmap = {a["ptr"]: b for a, b in zip(scenes[lba]["messages"], m.values())}
                return wmap, mmap
    return None


def enlarge(iso, lba, old_n, new_n):
    """Give a scene more sectors: patch the count byte of its table entry wherever it appears.
    Safe up to 16 sectors = 4 RAM banks ($7E-$81, the size of the game's own largest scene) and only
    into sectors that no other load-table entry claims."""
    pat = bytes([0x00, lba & 0xFF, lba >> 8, 0x04, 0x16, 0x00, old_n, 0x00])
    hits = 0
    i = iso.find(pat)
    while i >= 0:
        iso[i + 6] = new_n
        hits += 1
        i = iso.find(pat, i + 1)
    return hits


def typed_data(text):
    """A word the player types *against*, rather than reads.

    Full-width digits are the keypads and the numbers they dial or answer. The door quiz's list also
    holds part-typed shapes -- ０★, ０★★, ８★ -- where ★ stands for a digit not yet entered, and every
    typed-answer screen in the game carries a ☆ entry as its catch-all. All of it is matched, never
    shown: translating ★ put "Dummy F" and "8*" among the numbers on Katrina's first question, and ☆
    became the word "Star" in the middle of Napoleon's password list.
    """
    return bool(text) and all("\uff10" <= c <= "\uff19" or c in "\u2605\u2606" for c in text)


def kana_only(text):
    return bool(text) and all("\u30a1" <= c <= "\u30ff" or c == "\u30fc" for c in text)


# The rows of the katakana grid the player types names with on the Jordan search screen. A scene that
# contains them is that screen; plenty of ordinary scenes have katakana menu words, so the rows, not the
# count, are what identifies it.
KANA_GRID = {"アイウエオ", "イウエオ", "カキクケコ", "サシスセソ", "タチツテト", "ナニヌネノ", "ハヒフヘホ",
             "マミムメモ", "ヤユヨワン", "ラリルレロ", "ガギグゲゴ", "ザジズゼゾ", "ダヂヅデド", "バビブベボ",
             "パピプペポ"}


# A menu column is eight cells wide, so a word is cut off after sixteen letters -- measured in the
# emulator by putting a 24-letter word into the reception's object list and into the command menu
# below it, and counting what came back: "ABCDEFGHIJKLMNOP" both times. Nothing warns about this on
# the disc, the word is simply drawn until the column ends, which is how "About Buffalo restaurant"
# reached the player as "About Buffalo re".
MENU_WIDTH = 16


def build_scene(iso, sc, words_en, msgs_en, coding, report):
    base, loaded = sc["base"], sc["loaded"]
    free_end = sc["text_end"]
    wide = []
    # --- menu words -------------------------------------------------------------------------------
    # The computer name search: its word list is not menu words but the keyboard the player types with
    # and the dictionary the typed name is matched against, in one tree. tools/namesearch.py rewrites
    # both in the game's own full-width Latin, the way the videophone's digits already work, and
    # checks that every name is under a key that carries its first letter.
    dictionary = sum(1 for w in sc["words"] if w.get("jp") in KANA_GRID) >= 5
    repl, chain = namesearch.plan(iso, sc) if dictionary else ({}, {})
    # The first entry of every typed-answer tree is its fallback, and its first byte is what picks the
    # keyboard (tools/answers.py). It is never shown on a typed screen, so it stays as written.
    keep = answers.fallbacks(iso, sc)
    typed = answers.entries(iso, sc)
    inplace = moved = 0
    relocs = []
    for w in sc["words"]:
        if w["off"] in keep:
            continue
        if w["off"] in repl:                               # keyboard key or dictionary entry
            data = repl[w["off"]]
            if len(data) <= w["size"]:
                iso[base + w["off"]:base + w["off"] + w["size"] + 1] = (data + b"\xff").ljust(w["size"] + 1, b"\xff")
                inplace += 1
            else:
                relocs.append((w["off"], data))
            continue
        # Numbers are not text: these entries are what the player types against -- the digits of the
        # keypad and the values that are matched. Katrina's door quiz compares the typed number with
        # them, so translating them made every answer wrong however it was entered, and the videophone
        # showed no digits at all. They stay as they are.
        if typed_data(w.get("jp", "")):
            continue
        en = words_en.get(w["off"])
        if not en:
            continue
        if w["off"] in typed:                              # matched against the keyboard, never drawn
            data = answers.latin(en)
        else:
            if len(en) > MENU_WIDTH:
                wide.append(en)
            data = sncells.sjis_plain(en)
        if len(data) <= w["size"]:
            iso[base + w["off"]:base + w["off"] + w["size"] + 1] = (data + b"\xff").ljust(w["size"] + 1, b"\xff")
            inplace += 1
        else:
            relocs.append((w["off"], data))
    # A typed-answer screen sizes its field for the Japanese answer; the fields are widened once per
    # track (answers.apply) and this names anything that still could not be typed, or a fallback that
    # would pick the wrong keyboard -- either one is a puzzle that cannot be solved.
    stuck = answers.check(iso, sc, words_en)

    # --- messages -------------------------------------------------------------------------------
    # Pointers are arbitrary offsets into the loaded block, so a message may live in any free span:
    # the scene's own text regions, the last one extended to the end of what the scene loads.
    spans = [[lo, hi] for lo, hi in sc["regions"]]
    spans[-1][1] = loaded
    cursor = [lo for lo, _ in spans]
    chunks = {i: bytearray() for i in range(len(spans))}
    new_ptr = {}
    for m in sc["messages"]:
        data = coding.encode(msgs_en.get(m["ptr"]) or "...", nowait=m["jp"].rstrip().endswith("<82F5>"))
        for i, (lo, hi) in enumerate(spans):
            if cursor[i] + len(data) <= hi:
                new_ptr[m["ptr"]] = cursor[i]
                chunks[i] += data
                cursor[i] += len(data)
                break
        else:
            return f"  OVER BUDGET by {len(data)} bytes at message {m['ptr']:#x}"
    for off, data in relocs:                               # relocated menu words take what is left
        for i, (lo, hi) in enumerate(spans):
            if cursor[i] + len(data) + 1 <= hi:
                pos = cursor[i]
                chunks[i] += data + b"\xff"
                cursor[i] += len(data) + 1
                break
        else:
            return f"  OVER BUDGET: no room for a menu word"
        for j in range(sc["text_start"]):
            if iso[base + j] == 0xF1 and (iso[base + j + 1] | (iso[base + j + 2] << 8)) == off:
                iso[base + j + 1:base + j + 3] = pos.to_bytes(2, "little")
                moved += 1
    for g, nxt in chain.items():                           # show the keys in alphabetical order
        if nxt is not None:
            assert iso[base + g] == 0x20
            iso[base + g + 1:base + g + 3] = nxt.to_bytes(2, "little")
    for i, (lo, hi) in enumerate(spans):
        iso[base + lo:base + hi] = bytes(chunks[i]).ljust(hi - lo, b"\xff")
    for m in sc["messages"]:
        for c in m["cmds"]:
            iso[base + c + 3:base + c + 5] = new_ptr[m["ptr"]].to_bytes(2, "little")
    used = sum(len(c) for c in chunks.values())
    budget = sum(hi - lo for lo, hi in spans)
    report.append(f"scene {sc['lba']:#05x}: {len(sc['messages']):4d} msgs, words {inplace} in place / {moved} moved, "
                  f"{used:5d} of {budget:5d} bytes"
                  + (f"  CUT OFF at {MENU_WIDTH} letters: {', '.join(wide)}" if wide else "")
                  + (f"  UNTYPEABLE: {', '.join(stuck)}" if stuck else ""))
    return None


def main():
    coding = snhuff.Coding()
    scenes = {}
    for f in sorted(glob.glob("work/scenes/*.json")):
        sc = json.load(open(f))
        scenes[sc["lba"]] = sc
    isos = {2: open("disc/track02.iso", "rb").read(), 24: open("disc/track24.iso", "rb").read()}
    originals = {t: bytes(v) for t, v in isos.items()}
    sizes_before = {lba: sc["loaded"] for lba, sc in scenes.items()}
    report = []
    for t in isos:
        data, sizes, letters_at = snhack.apply(isos[t], coding, keyboard.masks())
        data, nn = snnames.apply(data)
        data, kb = keyboard.patch(data, letters_at)   # A-Z on the game's own name-entry keyboard
        isos[t] = bytearray(data)
        title = title_patch.patch(isos[t])            # the title menu, written into VRAM at runtime
        fields = answers.apply(isos[t])               # room to type the English answers, in every copy
    report.append(text_source())
    report.append(f"code: {sizes}, names {nn} bytes; {kb}")
    report.append(title)
    report.append(f"typed-answer fields widened to {answers.MAX}: {len(fields)} on each track")
    skipped = []
    lbas = sorted(scenes)
    for k, lba in enumerate(lbas):
        sc = scenes[lba]
        tr = translation_for(lba, scenes)
        if tr is None:
            skipped.append(lba)
            continue
        # the English may not fit the sectors the scene loads today; it may grow into the unclaimed
        # sectors before the next scene, at most to 16 (4 RAM banks)
        nxt = lbas[k + 1] if k + 1 < len(lbas) else lba + 16
        room = min(16, nxt - lba)
        r = None
        for n in range(sc["loaded"] // 0x800, room + 1):
            trial = {t: bytearray(iso) for t, iso in isos.items()}
            sc["loaded"] = n * 0x800
            for t in trial:
                r = build_scene(trial[t], sc, tr[0], tr[1], coding, report if t == 2 else [])
            if r is None:
                if n != sc["lba"] and n * 0x800 != json.load(open(f"work/scenes/{lba:03x}.json"))["loaded"]:
                    old = json.load(open(f"work/scenes/{lba:03x}.json"))["loaded"] // 0x800
                    for t in trial:
                        enlarge(trial[t], lba, old, n)
                    report[-1] += f"  (grown {old} -> {n} sectors)"
                isos.update(trial)
                break
            report.pop() if report and report[-1].startswith("  ") else None
        if r:
            report.append(f"scene {lba:#05x}: {r} -- left Japanese")
    # The disc keeps a second copy of some scenes, and for the name-search screen that is the copy the
    # game reads -- hardware showed the katakana keyboard while the patched bank sat unread. Build it
    # too, keyed to its own offsets by the Japanese each line replaces.
    tr = translation_for(0x0FE, scenes)
    # Scenes exist on the disc more than once, and the game reads the copy the scene table does not
    # name -- the name search proved it (sector 83), and Outer Heaven's entrance did it again on hardware
    # (0x1BE's twin at sector 275 of track 24: Japanese menu words drawn through the English renderer).
    # Seventeen scenes have such copies. Every copy is built, keyed to the scene's translation by the
    # Japanese it replaces, in the room the copy has: none of them can grow, so a scene that only fits
    # once grown is reported here rather than left to be found.
    bases = {sc["base"] for sc in scenes.values()}
    # every slot start on each track: the table-named scenes plus every copy, so a copy's room ends
    # where the next one begins
    slots = {}
    for t in isos:
        starts = set(bases)
        for lba in lbas:
            sc = scenes[lba]; head = originals[t][sc["base"]:sc["base"] + 48]; off = -1
            while True:
                off = originals[t].find(head, off + 1)
                if off < 0:
                    break
                if originals[t][off:off + sc["text_start"]] == originals[t][sc["base"]:sc["base"] + sc["text_start"]]:
                    starts.add(off)
        slots[t] = sorted(starts) + [len(originals[t])]
    for t, iso in isos.items():
        for lba in lbas:
            if lba in skipped:
                continue
            sc = scenes[lba]
            head = originals[t][sc["base"]:sc["base"] + 48]
            off = -1
            while True:
                off = originals[t].find(head, off + 1)
                if off < 0:
                    break
                if off in bases:
                    continue
                # A copy is a copy only if the whole script matches, not just a leading sector: three
                # places on track 24 start with the same 48 bytes as a scene and are something else
                # after 63 or 2048 bytes (0x0AE at sector 3, 0x1CE at 122, 0x27E at 205). Writing English
                # into those would be writing into whatever they really are.
                a = originals[t][sc["base"]:sc["base"] + sc["text_start"]]
                if originals[t][off:off + sc["text_start"]] != a:
                    continue
                # A copy is packed tighter than the scene it copies -- fewer records, and the next slot
                # follows straight after -- so its room is bounded by whatever comes next on this track,
                # not by the scene's own size. Given the scene's size, the last text span ran into the
                # next slot: 0x19E's twin at sector 243 wrote over 0x0FE at 254, 0x1DE's at 307 over 0x13E
                # at 318, 0x13E's at 147 over 0x09E at 158 (found by tools/verify_build.py, 22 Sep).
                nxt = min(x for x in slots[t] if x > off)
                limit = min(sizes_before[lba], nxt - off)
                copy = scene_copies.describe(iso, off, loaded=limit)
                if copy is not None:
                    # The copy is byte-identical to the scene through its script and word list, so those
                    # are the scene's. describe() finding them for itself picked a chance message chain
                    # *inside* the word list on 0x15E's and 0x1DE's twins, saw no words before it, and
                    # left every menu word Japanese -- the J-Division street on hardware.
                    copy["text_start"] = sc["text_start"]
                    copy["words"] = sc["words"]
                    copy["messages"] = [m for m in copy["messages"] if sc["text_start"] <= m["ptr"] < limit]
                    copy["regions"] = [[max(lo, sc["text_start"]), min(hi, limit)] for lo, hi in copy["regions"] if hi > sc["text_start"] and lo < limit]
                if copy is None:
                    report.append(f"copy of {lba:#05x} on track {t} at sector {off // 0x800}: NOT A SCENE?")
                    continue
                tr = translation_for(lba, scenes)
                w, m, nm, nw = scene_copies.translation(copy, sc, tr[0], tr[1])
                r = build_scene(iso, copy, w, m, coding, report)
                line = f"copy of {lba:#05x} on track {t} at sector {off // 0x800}: "
                if r:
                    report.append(line + r.strip() + "  -- THIS COPY STAYS JAPANESE")
                else:
                    report[-1] = line + report[-1].split(": ", 1)[1]
    if skipped:
        report.append(f"no translation for: {[hex(x) for x in skipped]}")
    if os.environ.get("VOICE", "1") != "0":
        import voices
        report.append(voices.apply(isos))
    else:
        report.append("voices: SKIPPED (VOICE=0) -- every spoken line in this image is Japanese")
    import credits
    report.append(credits.apply(isos))
    out = "build-en"
    os.makedirs(out, exist_ok=True)
    # Record what each scene actually ended up loading. Scenes that did not fit were grown into the
    # unclaimed sectors after them, so work/scenes/*.json no longer describes the built image --
    # anything checking the build (tools/verify_text.py) has to read the sizes from here instead.
    json.dump({f"{lba:#05x}": scenes[lba]["loaded"] for lba in lbas if lba not in skipped},
              open("work/scene_layout.json", "w"), indent=0)
    # Reset every track this stage does not build back to a link to the original. Later stages
    # (tools/intro_audio.py) replace a link with a real file when they swap a track, and a build that
    # kept whatever was left lying there would carry a swap forward after it had been removed from
    # PAIRS -- the revert silently not happening, which is worse than the swap.
    for f in os.listdir("disc"):
        if f.endswith(".bin") and "(Track 02)" not in f and "(Track 24)" not in f:
            dst = f"{out}/{f}"
            if os.path.lexists(dst):
                os.remove(dst)
            os.symlink(os.path.abspath(f"disc/{f}"), dst)
    shutil.copy(f"disc/{N}.cue", f"{out}/{N}.cue")
    for t, iso in isos.items():
        raw = open(f"disc/{N} (Track {t:02d}).bin", "rb").read()
        open(f"{out}/{N} (Track {t:02d}).bin", "wb").write(C.iso2bin(bytes(iso), raw))
    report.append("tracks 03-20 are now links to the Japanese originals: run tools/intro_audio.py and "
                  "tools/cutscene_dub.py before merging, or the intro and all 15 cutscenes ship in Japanese")
    print("\n".join(report))


if __name__ == "__main__":
    main()
